[2025-05-05T07:45:06.284+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T07:30:00+00:00 [queued]>
[2025-05-05T07:45:06.309+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T07:30:00+00:00 [queued]>
[2025-05-05T07:45:06.311+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-05T07:45:06.351+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-05 07:30:00+00:00
[2025-05-05T07:45:06.361+0000] {standard_task_runner.py:60} INFO - Started process 1564 to run task
[2025-05-05T07:45:06.368+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-05T07:30:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmprir_l2ic']
[2025-05-05T07:45:06.373+0000] {standard_task_runner.py:88} INFO - Job 50: Subtask fetch_velib_data
[2025-05-05T07:45:07.443+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T07:30:00+00:00 [running]> on host ebcb33ff74c6
[2025-05-05T07:45:09.186+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T07:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-05T07:30:00+00:00'
[2025-05-05T07:45:09.188+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T07:45:09.192+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-05T07:45:09.202+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T07:45:09.264+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-05T07:45:09.265+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/fetch_data.py", line 3, in <module>
[2025-05-05T07:45:09.271+0000] {subprocess.py:93} INFO -     from matplotlib.pylab import f
[2025-05-05T07:45:09.272+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'matplotlib'
[2025-05-05T07:45:09.275+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-05T07:45:09.508+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-05T07:45:09.515+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250505T073000, start_date=20250505T074506, end_date=20250505T074509
[2025-05-05T07:45:09.577+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 50 for task fetch_velib_data (Bash command failed. The command returned a non-zero exit code 1.; 1564)
[2025-05-05T07:45:09.610+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-05T07:45:10.015+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
