[2025-05-06T08:35:17.584+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T08:15:00+00:00 [queued]>
[2025-05-06T08:35:17.608+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T08:15:00+00:00 [queued]>
[2025-05-06T08:35:17.609+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-06T08:35:17.649+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-06 08:15:00+00:00
[2025-05-06T08:35:17.658+0000] {standard_task_runner.py:60} INFO - Started process 201 to run task
[2025-05-06T08:35:17.666+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-06T08:15:00+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmphunly6ph']
[2025-05-06T08:35:17.672+0000] {standard_task_runner.py:88} INFO - Job 109: Subtask fetch_velib_data
[2025-05-06T08:35:18.612+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T08:15:00+00:00 [running]> on host c5eb6d8dd177
[2025-05-06T08:35:20.096+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T08:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-06T08:15:00+00:00'
[2025-05-06T08:35:20.098+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T08:35:20.101+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-06T08:35:20.111+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T08:35:22.650+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-06T08:35:22.653+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/fetch_data.py", line 48, in <module>
[2025-05-06T08:35:22.665+0000] {subprocess.py:93} INFO -     fetch_data()
[2025-05-06T08:35:22.667+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/fetch_data.py", line 25, in fetch_data
[2025-05-06T08:35:22.679+0000] {subprocess.py:93} INFO -     raise Exception(f"Erreur API JCDecaux: {response.status_code} - {response.text}")
[2025-05-06T08:35:22.681+0000] {subprocess.py:93} INFO - Exception: Erreur API JCDecaux: 403 - { "error" : "Unauthorized" }
[2025-05-06T08:35:22.912+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-06T08:35:23.211+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-06T08:35:23.215+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250506T081500, start_date=20250506T083517, end_date=20250506T083523
[2025-05-06T08:35:23.255+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 109 for task fetch_velib_data (Bash command failed. The command returned a non-zero exit code 1.; 201)
[2025-05-06T08:35:23.266+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-06T08:35:23.526+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
