[2025-05-04T12:59:26.683+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-04T12:59:22.965610+00:00 [queued]>
[2025-05-04T12:59:26.697+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-04T12:59:22.965610+00:00 [queued]>
[2025-05-04T12:59:26.698+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-04T12:59:26.736+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-04 12:59:22.965610+00:00
[2025-05-04T12:59:26.742+0000] {standard_task_runner.py:60} INFO - Started process 446 to run task
[2025-05-04T12:59:26.748+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'manual__2025-05-04T12:59:22.965610+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmp1gh3odle']
[2025-05-04T12:59:26.752+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask fetch_velib_data
[2025-05-04T12:59:27.413+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-04T12:59:22.965610+00:00 [running]> on host ebcb33ff74c6
[2025-05-04T12:59:28.104+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T12:59:22.965610+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-04T12:59:22.965610+00:00'
[2025-05-04T12:59:28.107+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-04T12:59:28.111+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/bike-data-pipeline/***/dags/scripts/fetch_data.py']
[2025-05-04T12:59:28.123+0000] {subprocess.py:86} INFO - Output:
[2025-05-04T12:59:28.145+0000] {subprocess.py:93} INFO - python: can't open file '/opt/bike-data-pipeline/***/dags/scripts/fetch_data.py': [Errno 2] No such file or directory
[2025-05-04T12:59:28.148+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-04T12:59:28.285+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-04T12:59:28.291+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250504T125922, start_date=20250504T125926, end_date=20250504T125928
[2025-05-04T12:59:28.324+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task fetch_velib_data (Bash command failed. The command returned a non-zero exit code 2.; 446)
[2025-05-04T12:59:28.372+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-04T12:59:28.480+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
