[2025-05-05T06:17:34.631+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T06:00:00+00:00 [queued]>
[2025-05-05T06:17:34.641+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T06:00:00+00:00 [queued]>
[2025-05-05T06:17:34.641+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-05T06:17:34.659+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-05 06:00:00+00:00
[2025-05-05T06:17:34.664+0000] {standard_task_runner.py:60} INFO - Started process 1159 to run task
[2025-05-05T06:17:34.667+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-05T06:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmpek7s6ftx']
[2025-05-05T06:17:34.669+0000] {standard_task_runner.py:88} INFO - Job 37: Subtask fetch_velib_data
[2025-05-05T06:17:34.875+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T06:00:00+00:00 [running]> on host ebcb33ff74c6
[2025-05-05T06:17:35.152+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-05T06:00:00+00:00'
[2025-05-05T06:17:35.153+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T06:17:35.155+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-05T06:17:35.162+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T06:17:35.207+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-05T06:17:35.207+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/fetch_data.py", line 3, in <module>
[2025-05-05T06:17:35.209+0000] {subprocess.py:93} INFO -     from matplotlib.pylab import f
[2025-05-05T06:17:35.210+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'matplotlib'
[2025-05-05T06:17:35.212+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-05T06:17:35.269+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-05T06:17:35.272+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250505T060000, start_date=20250505T061734, end_date=20250505T061735
[2025-05-05T06:17:35.294+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 37 for task fetch_velib_data (Bash command failed. The command returned a non-zero exit code 1.; 1159)
[2025-05-05T06:17:35.322+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-05T06:17:35.498+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
