[2025-05-05T09:50:09.173+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T09:30:00+00:00 [queued]>
[2025-05-05T09:50:09.188+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T09:30:00+00:00 [queued]>
[2025-05-05T09:50:09.190+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-05T09:50:09.207+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-05 09:30:00+00:00
[2025-05-05T09:50:09.213+0000] {standard_task_runner.py:60} INFO - Started process 220 to run task
[2025-05-05T09:50:09.217+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-05T09:30:00+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmpp0fd8aho']
[2025-05-05T09:50:09.220+0000] {standard_task_runner.py:88} INFO - Job 70: Subtask fetch_velib_data
[2025-05-05T09:50:09.736+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-05T09:30:00+00:00 [running]> on host 6e22c01489ce
[2025-05-05T09:50:10.515+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T09:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-05T09:30:00+00:00'
[2025-05-05T09:50:10.517+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T09:50:10.520+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-05T09:50:10.527+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T09:50:10.572+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-05T09:50:10.572+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/fetch_data.py", line 3, in <module>
[2025-05-05T09:50:10.575+0000] {subprocess.py:93} INFO -     from matplotlib.pylab import f
[2025-05-05T09:50:10.576+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'matplotlib'
[2025-05-05T09:50:10.579+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-05T09:50:10.761+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-05T09:50:10.768+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250505T093000, start_date=20250505T095009, end_date=20250505T095010
[2025-05-05T09:50:10.808+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 70 for task fetch_velib_data (Bash command failed. The command returned a non-zero exit code 1.; 220)
[2025-05-05T09:50:10.839+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-05T09:50:11.079+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
