[2025-05-06T09:27:06.545+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-06T09:26:47.616532+00:00 [queued]>
[2025-05-06T09:27:06.605+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-06T09:26:47.616532+00:00 [queued]>
[2025-05-06T09:27:06.610+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-06T09:27:06.730+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-06 09:26:47.616532+00:00
[2025-05-06T09:27:06.748+0000] {standard_task_runner.py:60} INFO - Started process 360 to run task
[2025-05-06T09:27:06.761+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'manual__2025-05-06T09:26:47.616532+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmp5n9g33ae']
[2025-05-06T09:27:06.769+0000] {standard_task_runner.py:88} INFO - Job 120: Subtask fetch_velib_data
[2025-05-06T09:27:08.279+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-06T09:26:47.616532+00:00 [running]> on host 5fdd72692c9b
[2025-05-06T09:27:10.671+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T09:26:47.616532+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T09:26:47.616532+00:00'
[2025-05-06T09:27:10.682+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T09:27:10.688+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-06T09:27:10.713+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T09:27:26.912+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données
[2025-05-06T09:27:28.295+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-06T09:27:29.683+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250506T092647, start_date=20250506T092706, end_date=20250506T092729
[2025-05-06T09:27:29.871+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-06T09:27:30.410+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
