[2025-05-06T07:52:19.218+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-06T07:52:11.955942+00:00 [queued]>
[2025-05-06T07:52:19.237+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-06T07:52:11.955942+00:00 [queued]>
[2025-05-06T07:52:19.238+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-06T07:52:19.289+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-06 07:52:11.955942+00:00
[2025-05-06T07:52:19.301+0000] {standard_task_runner.py:60} INFO - Started process 123 to run task
[2025-05-06T07:52:19.313+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'manual__2025-05-06T07:52:11.955942+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmp2m53keqi']
[2025-05-06T07:52:19.319+0000] {standard_task_runner.py:88} INFO - Job 102: Subtask fetch_velib_data
[2025-05-06T07:52:20.380+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-06T07:52:11.955942+00:00 [running]> on host d74c6180b342
[2025-05-06T07:52:21.875+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T07:52:11.955942+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T07:52:11.955942+00:00'
[2025-05-06T07:52:21.878+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T07:52:21.882+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-06T07:52:21.900+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T07:52:24.369+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données
[2025-05-06T07:52:24.610+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-06T07:52:25.124+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250506T075211, start_date=20250506T075219, end_date=20250506T075225
[2025-05-06T07:52:25.263+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-06T07:52:25.603+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
