[2025-05-06T09:20:32.765+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T09:00:00+00:00 [queued]>
[2025-05-06T09:20:32.814+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T09:00:00+00:00 [queued]>
[2025-05-06T09:20:32.817+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-06T09:20:32.894+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-06 09:00:00+00:00
[2025-05-06T09:20:32.913+0000] {standard_task_runner.py:60} INFO - Started process 292 to run task
[2025-05-06T09:20:32.956+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-06T09:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmpgozsiwxk']
[2025-05-06T09:20:32.976+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask fetch_velib_data
[2025-05-06T09:20:34.481+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T09:00:00+00:00 [running]> on host 5fdd72692c9b
[2025-05-06T09:20:37.060+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T09:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-06T09:00:00+00:00'
[2025-05-06T09:20:37.074+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T09:20:37.085+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-06T09:20:37.133+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T09:20:49.139+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-06T09:20:49.142+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/fetch_data.py", line 15, in <module>
[2025-05-06T09:20:49.160+0000] {subprocess.py:93} INFO -     API_KEY = Variable.get("API_KEY")
[2025-05-06T09:20:49.162+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/***/models/variable.py", line 143, in get
[2025-05-06T09:20:49.164+0000] {subprocess.py:93} INFO -     raise KeyError(f"Variable {key} does not exist")
[2025-05-06T09:20:49.166+0000] {subprocess.py:93} INFO - KeyError: 'Variable API_KEY does not exist'
[2025-05-06T09:20:50.249+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-06T09:20:50.861+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-06T09:20:50.887+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250506T090000, start_date=20250506T092032, end_date=20250506T092050
[2025-05-06T09:20:51.083+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 119 for task fetch_velib_data (Bash command failed. The command returned a non-zero exit code 1.; 292)
[2025-05-06T09:20:51.268+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-06T09:20:51.940+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
