[2025-05-06T09:08:35.550+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T08:45:00+00:00 [queued]>
[2025-05-06T09:08:35.565+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T08:45:00+00:00 [queued]>
[2025-05-06T09:08:35.568+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-06T09:08:35.597+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-06 08:45:00+00:00
[2025-05-06T09:08:35.602+0000] {standard_task_runner.py:60} INFO - Started process 157 to run task
[2025-05-06T09:08:35.605+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-06T08:45:00+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmpqbx7y46z']
[2025-05-06T09:08:35.607+0000] {standard_task_runner.py:88} INFO - Job 117: Subtask fetch_velib_data
[2025-05-06T09:08:36.197+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-06T08:45:00+00:00 [running]> on host 5fdd72692c9b
[2025-05-06T09:08:37.123+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T08:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-06T08:45:00+00:00'
[2025-05-06T09:08:37.126+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T09:08:37.130+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-06T09:08:37.140+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T09:08:40.228+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-06T09:08:40.228+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/fetch_data.py", line 15, in <module>
[2025-05-06T09:08:40.235+0000] {subprocess.py:93} INFO -     API_KEY = Variable.get("API_KEY")
[2025-05-06T09:08:40.236+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.10/site-packages/***/models/variable.py", line 143, in get
[2025-05-06T09:08:40.238+0000] {subprocess.py:93} INFO -     raise KeyError(f"Variable {key} does not exist")
[2025-05-06T09:08:40.238+0000] {subprocess.py:93} INFO - KeyError: 'Variable API_KEY does not exist'
[2025-05-06T09:08:40.603+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-06T09:08:40.882+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-06T09:08:40.887+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250506T084500, start_date=20250506T090835, end_date=20250506T090840
[2025-05-06T09:08:40.912+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 117 for task fetch_velib_data (Bash command failed. The command returned a non-zero exit code 1.; 157)
[2025-05-06T09:08:41.071+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-06T09:08:41.224+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
