[2025-05-04T15:54:57.812+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-04T15:30:00+00:00 [queued]>
[2025-05-04T15:54:57.830+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-04T15:30:00+00:00 [queued]>
[2025-05-04T15:54:57.832+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-04T15:54:57.874+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-04 15:30:00+00:00
[2025-05-04T15:54:57.886+0000] {standard_task_runner.py:60} INFO - Started process 780 to run task
[2025-05-04T15:54:57.900+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'scheduled__2025-05-04T15:30:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmpzi_s6p3e']
[2025-05-04T15:54:57.910+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask fetch_velib_data
[2025-05-04T15:54:59.191+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data scheduled__2025-05-04T15:30:00+00:00 [running]> on host ebcb33ff74c6
[2025-05-04T15:55:00.798+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-04T15:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-04T15:30:00+00:00'
[2025-05-04T15:55:00.800+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-04T15:55:00.802+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/bike-data-pipeline/***/dags/scripts/fetch_data.py']
[2025-05-04T15:55:00.814+0000] {subprocess.py:86} INFO - Output:
[2025-05-04T15:55:00.856+0000] {subprocess.py:93} INFO - python: can't open file '/opt/bike-data-pipeline/***/dags/scripts/fetch_data.py': [Errno 2] No such file or directory
[2025-05-04T15:55:00.862+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-05-04T15:55:01.226+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-05-04T15:55:01.233+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250504T153000, start_date=20250504T155457, end_date=20250504T155501
[2025-05-04T15:55:01.284+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task fetch_velib_data (Bash command failed. The command returned a non-zero exit code 2.; 780)
[2025-05-04T15:55:01.301+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-04T15:55:01.685+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
