[2025-05-05T10:00:02.132+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-05T09:54:51.468646+00:00 [queued]>
[2025-05-05T10:00:02.143+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-05T09:54:51.468646+00:00 [queued]>
[2025-05-05T10:00:02.144+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-05T10:00:02.166+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-05 09:54:51.468646+00:00
[2025-05-05T10:00:02.171+0000] {standard_task_runner.py:60} INFO - Started process 305 to run task
[2025-05-05T10:00:02.179+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'manual__2025-05-05T09:54:51.468646+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmpwvc0znup']
[2025-05-05T10:00:02.190+0000] {standard_task_runner.py:88} INFO - Job 72: Subtask fetch_velib_data
[2025-05-05T10:00:02.719+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-05T09:54:51.468646+00:00 [running]> on host 6e22c01489ce
[2025-05-05T10:00:03.500+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-05T09:54:51.468646+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-05T09:54:51.468646+00:00'
[2025-05-05T10:00:03.504+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-05T10:00:03.506+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-05T10:00:03.516+0000] {subprocess.py:86} INFO - Output:
[2025-05-05T10:00:05.690+0000] {subprocess.py:93} INFO - Erreur lors de la récupération des données
[2025-05-05T10:00:05.857+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-05T10:00:06.084+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250505T095451, start_date=20250505T100002, end_date=20250505T100006
[2025-05-05T10:00:06.101+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-05T10:00:06.166+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
