[2025-05-06T08:39:40.312+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-06T08:39:34.576378+00:00 [queued]>
[2025-05-06T08:39:40.356+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-06T08:39:34.576378+00:00 [queued]>
[2025-05-06T08:39:40.357+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-06T08:39:40.459+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): fetch_velib_data> on 2025-05-06 08:39:34.576378+00:00
[2025-05-06T08:39:40.473+0000] {standard_task_runner.py:60} INFO - Started process 260 to run task
[2025-05-06T08:39:40.485+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'velib_fetch_data', 'fetch_velib_data', 'manual__2025-05-06T08:39:34.576378+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/velib_fetch_dag.py', '--cfg-path', '/tmp/tmpn0tm5at8']
[2025-05-06T08:39:40.495+0000] {standard_task_runner.py:88} INFO - Job 110: Subtask fetch_velib_data
[2025-05-06T08:39:41.651+0000] {task_command.py:423} INFO - Running <TaskInstance: velib_fetch_data.fetch_velib_data manual__2025-05-06T08:39:34.576378+00:00 [running]> on host c5eb6d8dd177
[2025-05-06T08:39:43.363+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='velib_fetch_data' AIRFLOW_CTX_TASK_ID='fetch_velib_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-06T08:39:34.576378+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-06T08:39:34.576378+00:00'
[2025-05-06T08:39:43.365+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-06T08:39:43.367+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/dags/scripts/fetch_data.py']
[2025-05-06T08:39:43.379+0000] {subprocess.py:86} INFO - Output:
[2025-05-06T08:39:46.320+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-06T08:39:46.321+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/fetch_data.py", line 48, in <module>
[2025-05-06T08:39:46.328+0000] {subprocess.py:93} INFO -     fetch_data()
[2025-05-06T08:39:46.330+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/scripts/fetch_data.py", line 25, in fetch_data
[2025-05-06T08:39:46.335+0000] {subprocess.py:93} INFO -     raise Exception(f"Erreur API JCDecaux: {response.status_code} - {response.text}")
[2025-05-06T08:39:46.336+0000] {subprocess.py:93} INFO - Exception: Erreur API JCDecaux: 403 - { "error" : "Unauthorized" }
[2025-05-06T08:39:46.482+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-06T08:39:46.858+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-06T08:39:46.865+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=velib_fetch_data, task_id=fetch_velib_data, execution_date=20250506T083934, start_date=20250506T083940, end_date=20250506T083946
[2025-05-06T08:39:46.930+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 110 for task fetch_velib_data (Bash command failed. The command returned a non-zero exit code 1.; 260)
[2025-05-06T08:39:46.954+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-06T08:39:47.295+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
